# version: "3.8"

services:
  nginx:
    # image: nginx:1.21.1
    image: nginx:1.27.2
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php

  php:
    build: ./docker/php
    user: "${UID}:${GID}" # 教科書にはないが、コンテナ内のユーザーをホストユーザーと一致させる設定を追加 (権限エラーの問題を解消する為)
    volumes:
      - ./src:/var/www/

  mysql:
    # image: mysql:8.0.26
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    # image: phpmyadmin/phpmyadmin
    image: phpmyadmin:5.2.3
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - mysql
    ports:
      - 8080:80
